name: CI

on:
  push:
    branches: [main]         # keep branch builds
    tags:     ['v*']         # NEW – run on any tag starting with v
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest -q

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install poetry pyinstaller

      - name: Build wheel & sdist
        run: |
          poetry install --without dev
          poetry build

      - name: Build single-file executable
        run: |
          pyinstaller --onefile src/chessf/cli.py \
                      --name chessf \
                      --console

      - name: Upload artifacts
        # safest: stick to the major tag and pick up bug-fixes
        uses: actions/upload-artifact@v4
        with:
          name: chessf-distribution
          path: |
            dist/*.whl
            dist/*.tar.gz
            dist/chessf*          # works on Linux and Windows
          if-no-files-found: warn # (optional) don’t fail the run

      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN }}
        run: poetry publish --username __token__ --password $POETRY_PYPI_TOKEN

