name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest -q

  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install packagers
        run: |
          pip install poetry pyinstaller

      - name: Build project
        run: |
          poetry install --no-dev
          poetry build

      - name: Build single-file exe
        run: |
          pyinstaller --onefile src/chessf/cli.py \
                      --name chessf \
                      --console

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chessf-distribution
          path: |
            dist/*.whl
            dist/*.tar.gz
            dist/chessf.exe
